version: '1.0'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    networks:
      - network


networks:
  network:
    driver: bridge
